"""init

Revision ID: a74edac0a8ca
Revises: 3231dc95ed86
Create Date: 2025-12-08 19:33:07.635852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74edac0a8ca'
down_revision: Union[str, None] = '3231dc95ed86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - FIXED ###
    op.add_column('property', sa.Column('province', sa.String(), nullable=True))
    op.add_column('property', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('property', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_column('property', 'cancel_policy')

    op.add_column('room', sa.Column('room_number', sa.String(), nullable=True))
    op.add_column('room', sa.Column('image', sa.String(), nullable=True))
    op.add_column('room', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_column('room', 'is_active')
    op.drop_column('room', 'image')
    op.drop_column('room', 'room_number')

    op.add_column('property', sa.Column('cancel_policy', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('property', 'longitude')
    op.drop_column('property', 'latitude')
    op.drop_column('property', 'province')
    # ### end Alembic commands ###
